# roles/mariadb/tasks/install.yml
---

- name: Add official MariaDB yum repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb
  when: ansible_os_family == 'RedHat'

- name: Install MariaDB keys
  apt_key:
    keyserver: "{{ mariadb_apt_keyserver }}"
    id: "{{ mariadb_apt_keyid }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add official MariaDB apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
    filename: mariadb
  register: mariadb_install_packages
  with_items: '{{mariadb_apt_repositories}}'
  when: ansible_os_family == 'Debian'

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
